#!/bin/bash

repository="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
branch="gh-pages"
folder="build"
app_link="https://nekz.me/iverb-stats"

git config --global user.name "gh-actions"
git config --global user.email "actions@github.com"

branch_exits=$(git ls-remote "https://github.com/${GITHUB_REPOSITORY}" | grep "refs/heads/${branch}")

if [ -n "${branch_exits}" ]; then
    echo 'Cloning existing branch...'
    git clone --single-branch --branch "${branch}" "${repository}" tmp
    mv tmp/.git "${folder}"/.git
    rm -rf tmp
    pushd "${folder}"
else
    echo "Creating non-existing branch ${branch}..."
    pushd "${folder}"
    git init -b "${branch}" && git remote add origin "https://github.com/${GITHUB_REPOSITORY}"
fi

git add --all
git commit -m "Update"
git push "${repository}" HEAD:"${branch}"

popd

echo "Pushed changes"
echo "App available at: ${app_link}"
